name: Build and Push Docker Images

on:
  push:
    branches: main

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from the repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          path: ./backend
          dockerfile: ./backend/Dockerfile
          repository: 'iptables.viz.backend'
          tags: |
            linux-latest
          push: true

  build-and-push-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from the repository
        uses: actions/checkout@v1
        with:
          ref: main

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          path: ./frontend
          dockerfile: ./frontend/Dockerfile
          repository: 'iptables.viz.frontend'
          tags: |
            linux-latest
          push: true
