name: Build, Push, and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend-image:
    # ... existing build and push steps ...

  build-and-push-frontend-image:
    # ... existing build and push steps ...

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend-image, build-and-push-frontend-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: main

      - name: Set up AKS kubectl
        uses: azure/aks-set-context@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_SP_ID }}","clientSecret":"${{ secrets.AZURE_SP_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","activeDirectoryEndpointUrl":"https://login.microsoftonline.com","resourceManagerEndpointUrl":"https://management.azure.com","activeDirectoryGraphResourceId":"https://graph.windows.net","sqlManagementEndpointUrl":"https://management.core.windows.net:8443/","galleryEndpointUrl":"https://gallery.azure.com/","managementEndpointUrl":"https://management.core.windows.net"}'
          cluster-name: 'kawhed'
          resource-group: 'test'

      - name: Deploy backend Helm chart
        run: |
          helm upgrade --install backend ./iptables-viz/backend/

      - name: Deploy frontend Helm chart
        run: |
          helm upgrade --install frontend ./iptables-viz/frontend/
