name: Build

on:
  push:
    branches: main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from the repository
        uses: actions/checkout@v1
        with:
          ref: main

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          path: ./backend
          dockerfile: ./backend/Dockerfile  # Correct path to Dockerfile
          repository: 'repo.api'
          tags: 'linux-latest'
          push: true
